### ISSUE TITLE
Lab3 - Azure : Erreur AZFD0005 sur AZ-FUNCTION 

### ISSUE THREAD

**Issue by PlugNPush** [tcs-france/workshop-efrei2023#2]
J'ai peut-être mal exécuté les étapes. J'aurais besoin d'indications pour faire marcher le auth-worker sur l'Azure Fonction.

EVTL spoiler ci-dessous.

Détail des opérations : 

Après m'être connecté avec az,

dans le dossier auth-worker:

dotnet restore auth-worker.csproj --runtime linux-x64
dotnet publish auth-worker.csproj -c Release --no-restore --runtime linux-x64 --no-self-contained -o ./output
cd output
zip -r publish.zip .
az functionapp deployment source config-zip --resource-group "Efrei-TCS-Workshop" --name "efrei-tcs-workshop-az-function" --src "publish.zip"

Après quelques minutes, un JSON de confirmation s'affiche.

De retour dans Azure Portal, une banderole rouge s'affiche disant "You have multiple critical notifications. Click to get more details".

La première : Microsoft.Azure.WebJobs.Script: Error building configuration in an external star... 
Impossible d'en savoir plus, le message refuse de s'ouvrir en entier.

La deuxième est très complète et accepte de se dérouler pour afficher ces informations : 

Error code
AZFD0005
Level
Error
Message
Error building configuration in an external startup class.
Details
Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> System.IO.FileLoadException : Could not load file or assembly 'auth-worker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
 at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext,String ilPath,String niPath,ObjectHandleOnStack retAssembly)
 at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<>c__DisplayClass14_1.<GetExtensionsStartupTypesAsync>b__0(AssemblyName assemblyName) at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 192
 at System.TypeNameParser.ResolveAssembly(String asmName,Func`2 assemblyResolver,Boolean throwOnError,StackCrawlMark& stackMark)
 at System.TypeNameParser.ConstructType(Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase,StackCrawlMark& stackMark)
 at System.TypeNameParser.GetType(String typeName,Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase,StackCrawlMark& stackMark)
 at System.Type.GetType(String typeName,Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase)
 at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 189
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53
 at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
 at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
 at System.Lazy`1.CreateValue()
 at System.Lazy`1.get_Value()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68
 at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362
 at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 246
 End of inner exception
Hit count
46
Timestamp
May 10, 2023 at 7:52:18 PM GMT+2
Help link
https://go.microsoft.com/fwlink/?linkid=2224847

Merci

**Comment by GurYN** [comment]
Le problème vient de là : `--runtime linux-x64`

L'Azure Function sur le portail à été créé pour s'executer sur un environnement Windows, hors le package a été compilé pour  une cible linux.

**Comment by PlugNPush** [comment]
J'y ai pensé à un moment...

Sauf que après avoir testé windows-x64, windows-x86, windows-x86_64, windows, windows-amd64, windows-i386, msdos et dos je me suis retrouvé à court d'idées sur le runtime à utiliser et j'ai gardé linux-x64 ... 😅

**Comment by GurYN** [comment]
Si tu es sur une machine Windows, alors ne mets pas d'argument --target.

Pour info, la target windows 64 est : `win-x64`

**Comment by PlugNPush** [comment]
Merci ! Avec win-x64 ça fonctionne effectivement
