### ISSUE TITLE
401 User Not Created

### ISSUE THREAD

**Issue by PlugNPush** [tcs-france/workshop-efrei2023#5]
<img width="1295" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/0b898950-99b9-4017-a5c6-ac4b4bb54aca">
<img width="456" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/16b7b1e3-a356-46aa-a088-f3f3c7ba701c">

La création d'utilisateur ne fonctionne plus après avoir supprimé le cache Redis, est-ce à cause du mail déjà enregistré ?

**Comment by GurYN** [comment]
Non, pas de soucis pour le mail. 

L'erreur vient de l'API exam-api, pas de l'API auth-api. Cette erreur 401 veux dire qu'il n'y a pas de compte enregistré dans le cache. Il faut repasser par la mire de création du compte utilisateur.

**Comment by PlugNPush** [comment]
<img width="1639" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/4de259f7-42ab-4029-9eda-a4b5d7781f1c">

C'est ce que j'ai fait, mais visiblement l'utilisateur ne se créé pas (4ème essai consécutif)

**Comment by PlugNPush** [comment]
C'est en lien avec l'Azure Function. Elle refuse de se lancer alors que je ne l'ai pas modifiée.

J'ai re-tenté de restore en win-x64, build dans le dossier output en win-x64, créer le zip et le publier sur l'azure function. Je me retrouve à nouveau avec une erreur. 

Pire encore, après avoir restore, build et run sur mon architecture, le programme refuse également de se lancer en local sur mon ordinateur ! 

<img width="697" alt="image" src="https://github.com/tcs-france/workshop-efrei2023/assets/31410359/86464233-8c9d-4be3-a28a-d40c6eef63c3">

**Comment by PlugNPush** [comment]
Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> System.IO.FileLoadException : Could not load file or assembly 'auth-worker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
 at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext,String ilPath,String niPath,ObjectHandleOnStack retAssembly)
 at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<>c__DisplayClass14_1.<GetExtensionsStartupTypesAsync>b__0(AssemblyName assemblyName) at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 192
 at System.TypeNameParser.ResolveAssembly(String asmName,Func`2 assemblyResolver,Boolean throwOnError,StackCrawlMark& stackMark)
 at System.TypeNameParser.ConstructType(Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase,StackCrawlMark& stackMark)
 at System.TypeNameParser.GetType(String typeName,Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase,StackCrawlMark& stackMark)
 at System.Type.GetType(String typeName,Func`2 assemblyResolver,Func`4 typeResolver,Boolean throwOnError,Boolean ignoreCase)
 at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 189
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53
 at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
 at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor)
 at System.Lazy`1.CreateValue()
 at System.Lazy`1.get_Value()
 at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68
 at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362
 at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 246
 End of inner exception

**Comment by PlugNPush** [comment]
Sur mon ordinateur plus rien ne fonctionne, j'ai réussi à relancer un déploiement sur Azure Functions avec win-x86 au lieu de win-x64 ...

**Comment by PlugNPush** [comment]
En théorie, j'ai répondu aux 10 questions avec le bon profil (email Efrei). J'attends la confirmation avant de détruire le Ressource Group.

**Comment by GurYN** [comment]
Oui, les réponses sont bien enregistrées

**Comment by GurYN** [comment]
> C'est en lien avec l'Azure Function. Elle refuse de se lancer alors que je ne l'ai pas modifiée.
> 
> J'ai re-tenté de restore en win-x64, build dans le dossier output en win-x64, créer le zip et le publier sur l'azure function. Je me retrouve à nouveau avec une erreur.
> 
> Pire encore, après avoir restore, build et run sur mon architecture, le programme refuse également de se lancer en local sur mon ordinateur !
> 
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/31410359/238495486-86464233-8c9d-4be3-a28a-d40c6eef63c3.png">

Sur cette erreur c'est normal car une Azure Function se lance avec la commande `func` en local

**Comment by PlugNPush** [comment]
En effet. C'est bon pour la suppression côté Azure ?

**Comment by GurYN** [comment]
Oui, tu peux supprimer ton infrastructure.
